### PR TITLE
[#23] Convert issue template to YAML

### LINKED ISSUE #23: [toggle-core] Update issue template for bugs using new issue form in a YAML file
Epic: https://github.com/pheature-flags/pheature-flags/issues/299 [toggle-core] Update issue template for bugs using new issue form in a YAML

In order to make easier the creation of bugs following a specific format, we should update the [markdown file](https://github.com/pheature-flags/pheature-flags/blob/1.0.x/.github/ISSUE_TEMPLATE/bug_report.md) into a YAML file.

See [Github Docs](https://docs.github.com/es/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms).

### PR DESCRIPTION
**Pull request by vblinden**
This fixes #23

### CODE REVIEW

**Comment by vblinden** [comment]
Sorry, forgot to rebase before making a pull request.

**Comment by pcs289** [comment]
@vblinden we have opened a [discussion](https://github.com/pheature-flags/pheature-flags/discussions/308) upon bug reports templates, PR will be merged when we reach consensus on it. Come join us there!

**Comment by pcs289** [comment]
Hi @vblinden, we have finally reached a consensus on the [Bug Report Discussion](https://github.com/pheature-flags/pheature-flags/discussions/308#discussioncomment-1460093), you will find more information on the discussion link. Please update the PR to follow the established convention

**Comment by pcs289** [comment]
We close this PR because the functionality it provides is already covered by another contribution. You can find more issues to collaborate with the project at [PheatureFlags issues page](https://github.com/pheature-flags/pheature-flags/issues). Thank you very much for your dedication and time! 🚀

**Pull request closed without merging**
